---

- name: make sure to become true
  include: ensure_become.yml
  
- name: configure (and possibly create) system account for interacting with the database
  include_tasks: user.yml

- name: deploy query files
  include_tasks: queries.yml
